# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Alas ====================

Alas:
  menu: 'list'
  page: 'setting'
  tasks:
    Alas:
      - Emulator
      - EmulatorInfo
      - Error
      - Optimization
    Restart:
      - Scheduler
    DataUpdate:
      - Scheduler
      - ItemStorage

# ==================== Daily ====================

Daily:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Cafe:
      - Scheduler
      - Cafe
      - Invitation
    Schedule:
      - Scheduler
      - Schedule
      - Choice1
      - Choice2
      - Choice3
      - Choice4
      - Choice5
      - Choice6
      - Choice7
    Shop:
      - Scheduler
      - NormalShop
      - TacticalChallengeShop
      
# ==================== Farm ====================

Farm:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Bounty:
      - Scheduler
      - Bounty
      - Highway
      - DesertRailroad
      - Schoolhouse
    Scrimmage:
      - Scheduler
      - Scrimmage
      - Trinity
      - Gehenna
      - Millennium
    TacticalChallenge:
      - Scheduler
      - TacticalChallenge
    Mission:
      - Scheduler

# ==================== Rewards ====================

Reward:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Circle:
      - Scheduler
    Task:
      - Scheduler
    Mail:
      - Scheduler

# ==================== Tool ====================

Tool:
  menu: 'collapse'
  page: 'tool'
  tasks:
    Momotalk:
      - Momotalk