# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Alas ====================

Alas:
  menu: 'list'
  page: 'setting'
  tasks:
    Alas:
      - Emulator
      - EmulatorInfo
      - Error
      - Optimization
    Restart:
      - Scheduler

# ==================== Daily ====================

Daily:
  menu: 'list'
  page: 'setting'
  tasks:
    Cafe:
      - Scheduler
      - Cafe
      - Invitation
    Circle:
      - Scheduler
    Mail:
      - Scheduler
    Bounty:
      - Scheduler
      - Bounty
      - Highway
      - DesertRailroad
      - Schoolhouse
    Scrimmage:
      - Scheduler
      - Scrimmage
      - Trinity
      - Gehenna
      - Millennium
    TacticalChallenge:
      - Scheduler
      - TacticalChallenge
    DataUpdate:
      - Scheduler
      - ItemStorage